modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU GPL 3.0"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "forgetest"
version = "${file.jarVersion}" #mandatory
displayName = "Forgetest" #mandatory
#updateJSONURL="http://myurl.me/"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
#logoFile="forge.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants" #optional
description = '''

'''
[[dependencies.forgetest]] #optional
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.forgetest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
